version: "3"

services:
  upload:
    container_name: sobekkseter-upload
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    volumes:
      - path_to_private_key_on_host:path_to_private_key_on_container # Persist host's private key in container
      - path_to_file_on_host:path_to_file_on_container # Persist most recent webcam image
    depends_on:
      - python
    restart: on-failure

  python:
    container_name: sobekkseter-python
    image: python:3.8-slim
    restart: on-failure
